export { default as SideBarTabConfiguration } from './SideBarTabConfiguration.vue'
export { default as SideBarTabComments } from './SideBarTabComments.vue'
export { default as SideBarTabOptions } from './SideBarTabOptions.vue'
export { default as SideBarTabShare } from './SideBarTabShare.vue'
export { default as SideBarTabActivity } from './SideBarTabActivity.vue'
export { default as SideBarTabDatePolls } from './SideBarTabDatePolls.vue'
