name: "Bug report: Nextcloud Polls"
description: "Submit a report and help us improve Polls"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ### 👍 Thank you for your time to contributing to our project!
        Please check the entered title, that it describes your bug as accurate as possible to help other users to find already submitted bug reports
  - type: checkboxes
    id: before-posting
    attributes:
      label: "⚠️ This issue respects the following points: ⚠️"
      description: All conditions are **required**. Your issue can be closed if these are checked incorrectly.
      options:
        - label: This is a **bug**, not a question or a configuration/webserver/proxy issue.
          required: true
        - label: This issue is **not** already reported on Github _(I've searched it)_.
          required: true
        - label: I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        # Bug description
        Please try to explain your bug as detailed as possible. This helps us to reproduce this error and get it fixed faster.
  - type: textarea
    id: bug-description
    attributes:
      label: What went wrong, what did you observe?
      description: |
        Provide a description of the bug you're experiencing. Describe, if you are a poll user or a poll owner.
        Don't just expect someone will guess what your specific problem is and provide full details.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect, how polls should behave instead?
      description: |
        Describe, what did you expect to happen, instead of the observed behavior.
        Help us to understand how this bug could be solved.
    validations:
      required: true
  - type: textarea
    id: reproduce-bug
    attributes:
      label: What steps does it need to replay this bug?
      description: |
        Try to describe as precisely as you can, what led to this bug, so that we are able to reproduce it.
        Describe the poll configuration and other relevant circumstances.
        The better your description is _(go 'here', click 'there'...)_ the faster you'll get an _(accurate)_ answer.
        A picture describes more than 1000 words: Add screenshots which illustrate the bug.
      value: |
        1.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        # Add some information about your Polls installation
  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      description: |
        How did you install the Polls version, you are referring to, especially when experiencing update errors
      options:
        - "Installed/updated from the appstore (Apps section of your site)"
        - "Installed/updated using occ"
        - "Installed/updated via extracting downloaded package to the apps folder"
    validations:
      required: true
  - type: dropdown
    id: install-type
    attributes:
      label: Installation type
      description: |
        Was it an update or a first time installation
      options:
        - "First time installation"
        - "Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)"
        - "Updated from previous major version (i.e. 3.x.x to 4.x.x)"
        - "Updated from a much older version (more than one major version)"
    validations:
      required: true
  - type: input
    id: polls-version
    attributes:
      label: Affected polls version
      placeholder: Your installed polls version
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        # Client environment
        This helps us to identify possible effects caused by the client environment.

        ⚠️ Please make sure browser extensions/plug-ins can be excluded as the bug source (especially script and ad blockers).

  - type: checkboxes
    id: client-browser
    attributes:
      label: Which browser did you use, when experiencing the bug?
      description: |
        Select **all** browsers you used, where the bug appeared.
      options:
      - label: "Firefox"
      - label: "Chrome"
      - label: "Chromium/Chromium based (i.e. Edge)"
      - label: "Safari"
      - label: "Other/Don't know"
  - type: input
    id: client-browser-other
    attributes:
      label: Other browser
      placeholder: i.e. Opera mobile

  - type: textarea
    id: client-logs
    attributes:
      label: Add your browser log here
      description: |
        Provide the content of your browser console or network tab in case of errors (see developer tools of your browser).
      placeholder: This will be automatically formatted into code for better readability.
      render: json

  - type: textarea
    id: client-additional-info
    attributes:
      label: Additional client environment information
      description: |
        Add additional information about your client environment (i.e. browser plug-ins).

  - type: markdown
    attributes:
      value: |
        ---
        # Server Environment
        This helps us to identify possible effects caused by the server environment.
  - type: dropdown
    id: server-nc-version
    attributes:
      label: NC version
      description: |
        Which Nextcloud Server version are you running.
      options:
        - "Nextcloud 27"
        - "Nextcloud 28"
        - "Nextcloud 29"
        - "Nextcloud 30"
        - "Nextcloud 31"
        - "Other/Don't know"
    validations:
      required: true
  - type: input
    id: server-nc-version-other
    attributes:
      label: Other Nextcloud version
      placeholder: i.e. Nextcloud 21.1.1

  - type: dropdown
    id: server-php
    attributes:
      label: PHP engine version
      description: |
        Select PHP engine version serving Nextcloud Server.
      options:
        - "PHP 8.0"
        - "PHP 8.1"
        - "PHP 8.2"
        - "PHP 8.3"
        - "Other/Don't know"
    validations:
      required: true
  - type: input
    id: server-php-other
    attributes:
      label: Other PHP version
      description: Add your _other_ PHP versoin
      placeholder: i.e. PHP 8.3

  - type: dropdown
    id: server-database
    attributes:
      label: Database engine
      description: |
        Select Database engine serving Nextcloud Server.
      options:
        - "MySQL"
        - "MariaDB"
        - "PostgreSQL"
        - "SQlite"
        - "Oracle"
        - "Other/Don't know"
    validations:
      required: true
  - type: input
    id: server-other-db-version
    attributes:
      label: Database Engine version or other Database
      description: Add your database engine version or _other_ PHP versoin
      placeholder: i.e. PostgreSQL 14.5

  - type: checkboxes
    id: server-user-backend
    attributes:
      label: Which user-backends are you using?
      description: |
        Select **all** user-backends Enabled on your Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
      - label: "Default user-backend _(database)_"
      - label: "LDAP/ Active Directory"
      - label: "SSO - SAML"
      - label: "Other/Don't know"

  - type: textarea
    id: server-nextcloud-log
    attributes:
      label: Add your nextcloud server log here
      description: |
        Provide Nextcloud logs lines, which can give information about the bug.
        Copy all relevant contents from `data/nextcloud.log` or copy the a RAW entries from `/settings/admin/logging` section:
      placeholder: This will be automatically formatted into code for better readability.
      render: json

  - type: textarea
    id: additional-environment-info
    attributes:
      label: Additional environment informations
      description: |
        Add additional information about your environment

  - type: markdown
    attributes:
      value: |
        ---
        # Collect some information about your Nextcloud installation
        This helps us to identify possible effects caused by other apps or your environment.

  - type: textarea
    id: nextcloud-configs
    attributes:
      label: Configuration report
      description: |
        Provide information about your configuration.
        To get this information, execute one of the following commands on the CLI:
        ```shell
        sudo -u www-data php occ config:list system
        php occ config:list system
        ./occ config:list system
        ```
      placeholder: This will be automatically formatted into code for better readability.
      render: json

  - type: textarea
    id: nextcloud-apps
    attributes:
      label: List of activated Apps
      description: |
        Provide information about your apps.
        To get this information, execute one of the following commands on the CLI:
        ```shell
        sudo -u www-data php occ app:list
        php occ app:list
        ./occ app:list
        ```
      placeholder: This will be automatically formatted into code for better readability.
      render: shell

  - type: textarea
    id: nextcloud-signing-status
    attributes:
      label: Nextcloud Signing status
      description: |
        Provide Nextcloud Signing status.
        Login as an admin user into your Nextcloud, then access this URL:
        ```shell
        https://yournextcloud.tld/index.php/settings/integrity/failed
        ```
      placeholder: This will be automatically formatted into code for better readability.
      render: shell

  - type: markdown
    attributes:
      value: |
        ---
        # Last words
        Add useful additional information, which does not fit into the prior sections.
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information which could be helpful to understand this issue
