name: 'Feature request: Nextcloud Polls'
description: 'Suggest your idea for the improvement of Polls'
labels: ['enhancement']

body:
  - type: markdown
    attributes:
      value: |
        ### 👍 Thank you for your time to contributing to our project!
        Please check the entered title, that it describes your request as accurate as possible to help other users to find already submitted feature requests
  - type: checkboxes
    id: before-posting
    attributes:
      label: '⚠️ This issue respects the following points: ⚠️'
      description: All conditions are **required**. Your issue can be closed if these are checked incorrectly.
      options:
        - label: I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).
          required: true
  - type: textarea
    id: user-story
    attributes:
      label: Describe the goal you'd like to achieve
      description: |
        Describe what (goal) you want to achieve and why (value). Please explain your goal and why this is valuable and 
        **do not** describe the solution you suggest. Try to use the [user story](https://en.wikipedia.org/wiki/User_story) pattern
      value: As a **[poll participant/poll owner/...]**, I want to **[be able to .../ don't want to ...]**, because **[it helps to ... /avoids ...]**.
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Describe possible solutions
      description: If you have a proposal for a way to get to the goal stated above, describe it here.
      placeholder: Suggest a solution, how your value can be earned
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add a screenshot or a mockup for your UI suggestion or add more context to understand the reason, why you think this is a valuable request.
