# SPDX-FileCopyrightText: 2022 Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
name: Setup composer and PHP
description: 'Setup PHP environment and install composer dependencies with caching'
inputs:
  php-version:
    description: 'PHP version (default: 8.2)'
    required: false
    default: '8.2'
  php-tools:
    description: 'Additional php tools'
    required: false
    type: string
  php-extensions:
    description: 'extensions to add to php'
    required: false
    type: string
  mode:
    description: 'Composer install mode (dev, production, default: dev)'
    required: false
    type: string
    default: 'dev'
  working-directory:
    description: 'deployment directory'
    required: false
    type: string
    default: ''

outputs:
  cache-hit:
    description: 'Return cache hit'
    value: ${{ steps.cache-composer.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Use or setup caching composer packages (${{ inputs.mode }})
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # version 5.0.3
      id: cache-composer
      env:
        cache-name: cache-composer-${{ inputs.mode }}
      with:
        path: vendor
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Set up php ${{ inputs.php-version }}
      uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
      with:
        php-version: ${{ inputs.php-version }}
        tools: ${{ inputs.php-tools }}
        extensions: ${{ inputs.php-extensions }}
        coverage: none

    - name: Install dev packages
      if: steps.cache-composer.outputs.cache-hit != 'true' && inputs.mode == 'dev'
      working-directory: ${{ inputs.working-directory }}
      run: composer i -o
      shell: bash

    - name: Install production packages
      if: steps.cache-composer.outputs.cache-hit != 'true' && inputs.mode == 'production'
      working-directory: ${{ inputs.working-directory }}
      run: composer i --no-dev -o
      shell: bash
