# SPDX-FileCopyrightText: 2022 Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
name: Read polls version from info.xml
description: 'Read polls app version from info.xml and compare it to tag name'
inputs:
  skip-check:
    description: Do not check tag against version
    required: false
    type: boolean
    default: false

outputs:
  app-version:
    description: 'Version string from app'
    value: ${{ steps.appinfo.outputs.info }}
  tag-version:
    description: 'Version string from tag'
    value: ${{ steps.gettag.outputs.VERSION }}

runs:
  using: 'composite'
  steps:
    - name: Get app version from appinfo/info.xml
      id: appinfo
      uses: mavrosxristoforos/get-xml-info@2.0
      with:
        xml-file: 'appinfo/info.xml'
        xpath: '//info//version'

    - name: Get tag name
      id: gettag
      run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Compare versions
      if: ${{ !inputs.skip-version && format('v{0}', steps.appinfo.outputs.info) != steps.gettag.outputs.VERSION }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('App version ${{ format('v{0}', steps.appinfo.outputs.info) }} is not equal to tag name ${{ steps.gettag.outputs.VERSION }}!')
