name: Build

on: 
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [14.x]
        npm-versions: [7]

    name: build release
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-versions }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-versions }}
