name: Build

on: 
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [14.x]
        npm-versions: [7]

    name: build release
    steps:
    - uses: actions/checkout@v2
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'appinfo/info.xml'
        xpath: '//info//version'
    - name: Check version
      run: echo ${{ steps.getxml.outputs.info }}
