name: Build

on: 
  push:
    tags:
      v*-beta*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [14.x]
        npm-versions: [7]

    name: build release
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-versions }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-versions }}
    - name: Set up npm ${{ matrix.npm-versions }}
      run: npm i -g npm@"${{ matrix.npm-versions }}"
    - name: create release package
      run: make appstore
