name: Build

on: 
  push:
    tags:
      v*-beta*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [14.x]
        npm-versions: [7]

    name: build release
    steps:
    - uses: actions/checkout@v2
    - name: Get app version
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'appinfo/info.xml'
        xpath: '//info//version'
    - name: Get tag name
      id: gettag
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Check correct app version
      if: ${{ join(['v', steps.getxml.outputs.info]) }} != ${{ steps.gettag.outputs.VERSION }}
      run: echo App version ${{ join(['v', steps.getxml.outputs.info]) }} is not equal to tag name ${{ steps.gettag.outputs.VERSION }} |
        exit 1
    - name: Print version
      run: echo App version ${{ join(['v', steps.getxml.outputs.info]) }}, Tag name ${{ steps.gettag.outputs.VERSION }}